### ISSUE TITLE
MassiveEconomy v2.00 R1 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/MassiveEconomy#2]
MassiveEconomy v2.00 R1 Upcoming Features:
- [x] MySQL support
- [x] Language support
- [x] MassiveEconomy events
- [x] :lock: secret feature
- [x] :lock: secret feature
- [ ] :lock: secret feature
- [ ] :lock: secret feature
- [ ] :lock: secret feature
- [ ] :lock: secret feature
- [ ] :lock: secret feature
